# Dependabot configuration for obsidian-logging
# Monitors dependencies for Rust (Cargo), Rust toolchain, and GitHub Actions
# See: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor Rust dependencies in Cargo.toml
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "ljantzen"
    assignees:
      - "ljantzen"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Ignore major version updates for now (can be enabled later)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Monitor Rust toolchain updates
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "ljantzen"
    assignees:
      - "ljantzen"
    commit-message:
      prefix: "rust-toolchain"
      include: "scope"

  # Monitor GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "ljantzen"
    assignees:
      - "ljantzen"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Group minor and patch updates for actions
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
