[package]
name = "olog"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["unstable-locales"] }
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0"
serde_yaml = "0.9"
regex = "1.10"
lazy_static = "1.4"

