name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v5
        with:
          persist-credentials: false
      - name: Build
        run: cargo build --verbose --release --workspace
      - name: Run tests
        run: cargo test --verbose --workspace
